### ISSUE TITLE
What does CNOE stand for? Is it an acronym?

### ISSUE THREAD

**Issue by knksmith57** [cnoe-io/website#10]
I'm sure this is obvious to folks that actively engage with the project, but I can't find an explanation of what CNOE means _anywhere_.

**Comment by nimakaviani** [comment]
it started as an acronym for "Cloud Native Operational Excellence", but the work has expanded to go beyond operational needs, that's why we are not particularly referring to the full reference as much.

**Comment by knksmith57** [comment]
Thanks for the context!
