### ISSUE TITLE
First draft of IDP capability map

### ISSUE THREAD

**Issue by cbleach** [cnoe-io/website#3]
IDP Definition
Capability Map
Context about the space (growth, challenges)

**Comment by jessesanford** [comment]
Draft of capability "Descriptions": https://docs.google.com/document/d/1q3fHaXsMNN8oFdiibu_1XnMscCfs78kVP2KcQFyUZuk/edit?usp=sharing

**Comment by nimakaviani** [comment]
finalized first version here: cabd76a2e8e79db274666cd3ed9f36e92474f34c
